# Generated by Django 4.1.6 on 2023-02-05 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_cities_options_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'ordering': ('name',), 'verbose_name_plural': 'Cities'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='craeted_by',
            new_name='created_by',
        ),
    ]
